[font]
builtin_box_drawing = true
# draw_bold_text_with_bright_colors = true
size = 13.0

[font.bold]
family = "IntoneMonoNerdFontMono"
style = "Bold"
#
[font.bold_italic]
family = "IntoneMonoNerdFontMono"
style = "Bold Italic"
#
[font.italic]
family = "IntoneMonoNerdFontMono"
style = "Italic"

[font.normal]
family = "IntoneMonoNerdFontMono"
style = "Regular"

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "(magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true

[[hints.enabled]]
action = "Copy"
post_processing = false
regex = 'registry\.dev\.rafay-edge\.net\S+'

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[scrolling]
history = 10000
# multieplier = 2

[window]
decorations = "none"
decorations_theme_variant = "Light"
dynamic_padding = true
dynamic_title = true
opacity = 0.95

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0

[window.position]
x = 0
y = 0
